<a href="https://colab.research.google.com/github/KapilDhondi/KapilDhondi/blob/main/Numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1. Import the numpy package under the name np
import numpy as np


In [ ]:
#2. Print the numpy version and the configuration
np.__version__,np.show_config

('1.21.6', <function numpy.__config__.show>)

In [ ]:
#3. Create a null vector of size 10
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#4. How to find the memory size of any array 
arr1.size,arr1.itemsize

(10, 8)

In [ ]:
#5. How to get the documentation of the numpy add function from the command line?
np.info(arr1)

class:  ndarray
shape:  (10,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x1dfca30
byteorder:  little
byteswap:  False
type: float64


In [ ]:
#6. Create a null vector of size 10 but the fifth value which is 1
arr2 = np.zeros(10)
arr2[4] = 1
arr2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#7. Create a vector with values ranging from 10 to 49
arr3 = np.arange(10,50)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#8. Reverse a vector (first element becomes last)
arr4 = np.arange(1,10)
arr4[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
arr5 = np.arange(0,9).reshape(3,3)
arr5


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
arr6 = [1,2,0,0,4,0]
np.nonzero(arr6)

(array([0, 1, 4]),)

In [ ]:
#11. Create a 3x3 identity matrix
arr7 = np.eye(3,3)
arr7


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#12. Create a 3x3x3 array with random values
arr8 = np.random.random(27).reshape(3,3,3)
arr8

array([[[0.37476219, 0.82947725, 0.02687743],
        [0.5984318 , 0.66721909, 0.08307934],
        [0.74624598, 0.27467689, 0.9649668 ]],

       [[0.98081608, 0.56157608, 0.28416824],
        [0.93406174, 0.91184786, 0.47848634],
        [0.76097151, 0.63394338, 0.52331253]],

       [[0.70903118, 0.15665721, 0.24604231],
        [0.84290122, 0.51923711, 0.53704782],
        [0.07287589, 0.99444846, 0.76531326]]])

In [ ]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
arr9 = np.random.random(100).reshape(10,10)
arr9,arr9.min(),arr9.max()

(array([[0.12260095, 0.97203447, 0.68644797, 0.3049513 , 0.27672408,
         0.31724231, 0.33219182, 0.80690979, 0.59395476, 0.58608935],
        [0.12306064, 0.61296694, 0.83733091, 0.48632425, 0.38630457,
         0.4046224 , 0.74337424, 0.78405869, 0.37764684, 0.74347661],
        [0.83565061, 0.80720081, 0.50636744, 0.42777079, 0.01608024,
         0.5589034 , 0.10559594, 0.39761024, 0.83367095, 0.078544  ],
        [0.83736225, 0.69832822, 0.74551596, 0.94893922, 0.01472232,
         0.72288013, 0.36605789, 0.17967276, 0.72173701, 0.09722406],
        [0.65702203, 0.36847099, 0.47414547, 0.05324066, 0.87391648,
         0.719826  , 0.57157208, 0.39570891, 0.93305858, 0.66078574],
        [0.15859524, 0.73702454, 0.51079029, 0.67616433, 0.50235045,
         0.781884  , 0.36012594, 0.05647472, 0.49842953, 0.1983405 ],
        [0.52947411, 0.35812325, 0.37444978, 0.3592056 , 0.02761289,
         0.29956109, 0.45804772, 0.73864172, 0.96759408, 0.11469077],
        [0.44681036, 0.1533

In [ ]:
#14. Create a random vector of size 30 and find the mean value
arr10 = np.random.randint(100,size=30)
arr10.mean()

53.6

In [ ]:
#15. Create a 2d array with 1 on the border and 0 inside
arr11 = np.ones((5,5))
arr11[1:-1,1:-1] = 0
arr11


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#16. How to add a border (filled with 0's) around an existing array?
arr12 = np.ones((5,5))
arr12_1 = np.pad(arr12,pad_width=1,mode="constant",constant_values=0)
arr12_1

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#17. What is the result of the following expression?
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# 0.3 == 3 * 0.1

print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


In [ ]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
arr13 = np.diag([1,2,3,4],k=-1)
arr13

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
arr14 = np.zeros((8,8),dtype=int)
arr14[1::2,::2] = 1
arr14[::2,1::2] = 1
arr14


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
arr15 = np.unravel_index(100, (6,7,8))
arr15

(1, 5, 4)

In [ ]:
#21. Create a checkerboard 8x8 matrix using the tile function
arr16 = np.tile(np.array([[0,1],[1,0]]),(4,4))
arr16.shape


(8, 8)

In [ ]:
#22. Normalize a 5x5 random matrix
arr17 = np.arange(1,26).reshape(5,5)
arr17_normlz = []
for i in range(len(arr17)):
  for j in range(len(arr17[i])):
    arr17_normlz.append(((arr17[i][j])-arr17.min())/(arr17.max()-arr17.min()))
arr17_normlzd=np.array(arr17_normlz).reshape(5,5)
arr17_normlzd

array([[0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667],
       [0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ],
       [0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333],
       [0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667],
       [0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ]])

In [ ]:
# modified code of question 22
ar = np.random.randint(100,size=(5,5))
def normalize(array):
  l = []
  for i in range(len(array)):
    for j in range(len(array[i])):
      l.append(((array[i][j])-array.min())/(array.max()-array.min()))
  l_nlzd = np.array(l).reshape(array.shape)
  return l_nlzd
print(ar)
print(normalize(ar))

[[15 36 83 42 29]
 [54 49 60 62 67]
 [32 79 32 95 65]
 [ 4  9 45 54 27]
 [56 39 35 22 36]]
[[0.12087912 0.35164835 0.86813187 0.41758242 0.27472527]
 [0.54945055 0.49450549 0.61538462 0.63736264 0.69230769]
 [0.30769231 0.82417582 0.30769231 1.         0.67032967]
 [0.         0.05494505 0.45054945 0.54945055 0.25274725]
 [0.57142857 0.38461538 0.34065934 0.1978022  0.35164835]]


In [ ]:
nr = (ar - np.mean (ar)) / (np.std (ar))
print(nr)

[[-1.34911823 -0.40724712  1.7007501  -0.13814109 -0.72120416]
 [ 0.40007096  0.17581594  0.66917699  0.758879    0.98313403]
 [-0.58665114  1.52134609 -0.58665114  2.23896216  0.89343202]
 [-1.84247928 -1.61822426 -0.00358808  0.40007096 -0.81090617]
 [ 0.48977297 -0.27269411 -0.45209813 -1.03516119 -0.40724712]]


In [ ]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [ ]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
matrix1 = np.arange(15).reshape(5,3)
matrix2 = np.arange(15,21).reshape(3,2)
dot_p = np.dot(matrix1,matrix2)
print(dot_p)



[[ 55  58]
 [208 220]
 [361 382]
 [514 544]
 [667 706]]


In [ ]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.
arr18 = np.arange(11)
arr18[(3 < arr18) & (arr18 < 8)] *= -1
print(arr18)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [ ]:
#26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#27. Consider an integer vector Z, which of these expressions are legal?
Z**Z , 
2 << Z >> 2 ,
Z <- Z ,
1j*Z ,
Z/1/1 ,
Z<Z>Z ,

In [ ]:
# Answer is 1j*Z

In [ ]:
#28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-9.22337204e+18])

In [ ]:
#29. How to round away from zero a float array ?
arr19 = np.array([32.11, 51.5, 0.112])
np.round(arr19,0)


array([32., 52.,  0.])

In [ ]:
#30. How to find common values between two arrays? (★☆☆)
#(hint: np.intersect1d)
arr20 = np.array([5,10,15,20,25,30,35,40,45,50])
arr21 = np.array([10,20,30,40,50,60,70,80,90,100])
co_arr = np.intersect1d(arr20,arr21)
print(f"1st array is \n{arr20}")
print(f"2nd array is \n{arr21}")
print(f"common values in both arrays \n{co_arr}")

1st array is 
[ 5 10 15 20 25 30 35 40 45 50]
2nd array is 
[ 10  20  30  40  50  60  70  80  90 100]
common values in both arrays 
[10 20 30 40 50]


In [ ]:
#31. How to ignore all numpy warnings (not recommended)? (★☆☆)
#(hint: np.seterr, np.errstate)
Array1 = np.array([6, 2, 0])
Array2 = np.array([3, 2, 0])
np.seterr(invalid='ignore')
np.divide(Array1, Array2)

array([ 2.,  1., nan])

In [ ]:
#32. Is the following expressions true? (★☆☆)
#(hint: imaginary number)
np.sqrt(-1) == np.emath.sqrt(-1)  # output will be false

False

In [ ]:
#33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
#(hint: np.datetime64, np.timedelta64)
import numpy as np

# for today
TD = np.datetime64('today', 'D')
print("Today: ", TD)

# for yesterday
YD = np.datetime64('today', 'D')
- np.timedelta64(1, 'D')

print("Yestraday: ", YD)

# for tomorrow
TW = np.datetime64('today', 'D')
+ np.timedelta64(1, 'D')

print("Tomorrow: ", TW)



Today:  2022-06-09
Yestraday:  2022-06-09
Tomorrow:  2022-06-09


In [ ]:
#34. How to get all the dates corresponding to the month of July 2016? (★★☆)
#(hint: np.arange(dtype=datetime64['D']))
july = np.arange('2016-07','2016-08',dtype='datetime64[D]')
for i in july:
  print(i)

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


In [ ]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
#(hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))
a = 10
b = 20
np.add(a,b)
np.multiply(np.add(a,b),np.divide(np.negative(a),2))

-150.0

In [ ]:
#36. Extract the integer part of a random array using 5 different methods (★★☆)
#(hint: %, np.floor, np.ceil, astype, np.trunc)
arr36 = np.random.uniform(0,10,10)



In [ ]:
arr36

array([5.46699942, 3.72353228, 2.01109197, 3.92867327, 1.20787772,
       7.94788409, 2.51978759, 3.63752253, 9.64455947, 9.06747711])

In [ ]:
print(arr36 - arr36%1)
print(arr36//1)
print(np.floor(arr36))
print(arr36.astype(int))
print(np.trunc(arr36))


[5. 3. 2. 3. 1. 7. 2. 3. 9. 9.]
[5. 3. 2. 3. 1. 7. 2. 3. 9. 9.]
[5. 3. 2. 3. 1. 7. 2. 3. 9. 9.]
[5 3 2 3 1 7 2 3 9 9]
[5. 3. 2. 3. 1. 7. 2. 3. 9. 9.]


In [ ]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
#(hint: np.arange)
arr37 = np.zeros((5,5))
arr37 += np.arange(5)
print(arr37) 

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
arr_37 = np.tile(np.arange(0, 5), (5,1))
print(arr_37)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
#38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
#(hint: np.fromiter)
def generate():
    for i in range(1,11):
        yield i
arr38 = np.fromiter(generate(),dtype=int,count=-1)
print(arr38)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
#(hint: np.linspace)
arr39 = np.linspace(0,1,11,endpoint=False)[1:]
print(arr39)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
#40. Create a random vector of size 10 and sort it (★★☆)
arr40 = np.random.randint(0,100,10)
arr40.sort()
print(arr40)

[13 20 32 33 37 39 54 89 89 90]


In [ ]:
#41. How to sum a small array faster than np.sum? (★★☆)
#(hint: np.add.reduce)
arr41 = np.arange(10)
np.add.reduce(arr41)

45

In [ ]:
#42. Consider two random array A and B, check if they are equal (★★☆)
#(hint: np.allclose, np.array_equal)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
eq1 = np.allclose(A,B)
eq2 = np.array_equal(A,B)
print(eq1)
print(eq2)

False
False


In [ ]:
#43. Make an array immutable (read-only) (★★☆)
#(hint: flags.writeable)
arr43 = np.zeros(10)
arr43.flags.writeable = False
arr43[0] = 1

ValueError: ignored

In [ ]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
#(hint: np.sqrt, np.arctan2)
arr44 = np.random.random((10,2))
X,Y = arr44[:,0],arr44[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.32115601 0.2140142  0.40252224 0.83580709 0.82403215 1.09209375
 0.9249925  0.38721345 1.00400049 1.06228565]
[1.34356436 0.40921479 0.79906889 0.5309112  0.77388387 0.52484898
 0.16700835 0.08427927 1.20601948 1.03946471]


In [ ]:
#45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#(hint: argmax)
arr45 = np.random.random(10)
print(arr45[arr45.argmax()])
print("Array before replacing :" , arr45)
arr45[arr45.argmax()] = 0
print("Array after replacing :" , arr45)

0.9430414956892672
Array before replacing : [0.88939075 0.58532243 0.6256947  0.05485476 0.84227684 0.09308721
 0.9430415  0.35383633 0.65864681 0.71814929]
Array after replacing : [0.88939075 0.58532243 0.6256947  0.05485476 0.84227684 0.09308721
 0.         0.35383633 0.65864681 0.71814929]


In [ ]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
#(hint: np.meshgrid)
arr46 = np.zeros((5,5), [('x',float),('y',float)])
arr46['x'], arr46['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(arr46)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
#(hint: np.subtract.outer)
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [ ]:
#48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
#(hint: np.iinfo, np.finfo, eps)
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
#49. How to print all the values of an array? (★★☆)
#(hint: np.set_printoptions)
np.set_printoptions(threshold=float("inf"))
arr49 = np.zeros((40,40))
print(arr49)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#50. How to find the closest value (to a given scalar) in a vector? (★★☆)
#(hint: argmin)
arr50 = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(arr50-v)).argmin()
print(arr50[index])

11


In [ ]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
#(hint: dtype)
arr51 = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(arr51)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  import sys


In [ ]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
#(hint: np.atleast_2d, T, np.sqrt)
arr52 = np.random.random((10,2))
X,Y = np.atleast_2d(arr52[:,0], arr52[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

In [ ]:
# another way with scipy
import scipy

import scipy.spatial

arr52 = np.random.random((10,2))
D = scipy.spatial.distance.cdist(arr52,arr52)
print(D)

[[0.         0.33021003 0.93500228 0.9147575  0.51091224 0.62109535
  0.16076333 1.07867476 0.69477366 0.6446068 ]
 [0.33021003 0.         0.7482383  1.04915318 0.18076092 0.65148119
  0.39056365 0.90934077 0.40347776 0.55481393]
 [0.93500228 0.7482383  0.         0.89902526 0.69856318 0.53896061
  0.84768847 0.16441513 0.43401593 0.3372661 ]
 [0.9147575  1.04915318 0.89902526 0.         1.16086175 0.43645625
  0.75482261 0.910391   1.08996194 0.65203587]
 [0.51091224 0.18076092 0.69856318 1.16086175 0.         0.73819377
  0.56214742 0.86295421 0.28795214 0.58956216]
 [0.62109535 0.65148119 0.53896061 0.43645625 0.73819377 0.
  0.47254985 0.61292141 0.6543757  0.22885987]
 [0.16076333 0.39056365 0.84768847 0.75482261 0.56214742 0.47254985
  0.         0.97911654 0.68197123 0.53198549]
 [1.07867476 0.90934077 0.16441513 0.910391   0.86295421 0.61292141
  0.97911654 0.         0.5953933  0.44985016]
 [0.69477366 0.40347776 0.43401593 1.08996194 0.28795214 0.6543757
  0.68197123 0.595393

In [ ]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
#(hint: astype(copy=False))
arr53 = (np.random.rand(10)*100).astype(np.float32)
Y = arr53.view(np.int32)
Y[:] = arr53
print(Y)

[38 10 38 32 42 99 61 51 33 83]


In [ ]:
#54. How to read the following file? (★★☆)
#(hint: np.genfromtxt)
""" 1, 2, 3, 4, 5
    6,  ,  , 7, 8
     ,  , 9,10,11 """
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
arr54 = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(arr54)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  # This is added back by InteractiveShellApp.init_path()


In [ ]:
#55. What is the equivalent of enumerate for numpy arrays? (★★☆)
#(hint: np.ndenumerate, np.ndindex)
arr55 = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(arr55):
    print(index, value)
for index in np.ndindex(arr55.shape):
    print(index, arr55[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
#56. Generate a generic 2D Gaussian-like array (★★☆)
#(hint: np.meshgrid, np.exp)
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [ ]:
#57. How to randomly place p elements in a 2D array? (★★☆)
#(hint: np.put, np.random.choice)
n = 10
p = 3
arr57 = np.zeros((n,n))
np.put(arr57, np.random.choice(range(n*n), p, replace=False),1)
print(arr57)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#58. Subtract the mean of each row of a matrix (★★☆)
#(hint: mean(axis=,keepdims=))
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[ 0.43526484, -0.36651052, -0.33220364,  0.48092258,  0.47204824,
         0.2596875 , -0.39395752,  0.01573891, -0.12737907, -0.44361132],
       [-0.17107786, -0.37901215, -0.09813451,  0.09887733,  0.37708746,
         0.29399419,  0.00487107,  0.24976682, -0.08007428, -0.29629806],
       [ 0.09089237,  0.36975417, -0.38255897,  0.40763454, -0.28018704,
         0.06343826, -0.50515754,  0.42389584, -0.14573425, -0.04197738],
       [-0.02375678, -0.42941358,  0.44613459,  0.0679272 , -0.22772922,
         0.01653819, -0.42214898,  0.063335  ,  0.03202143,  0.47709216],
       [-0.278345  , -0.22211307,  0.084715  ,  0.58330582,  0.35904953,
        -0.17206501,  0.43811807, -0.29384688, -0.35063819, -0.14818028]])

In [ ]:
#59. How to sort an array by the nth column? (★★☆)
#(hint: argsort)
arr59 = np.random.randint(0,10,(3,3))
print(arr59)
print(arr59[arr59[:,1].argsort()])

[[1 3 4]
 [4 2 5]
 [2 7 1]]
[[4 2 5]
 [1 3 4]
 [2 7 1]]


In [ ]:
#60. How to tell if a given 2D array has null columns? (★★☆)
#(hint: any, ~)
arr60 = np.random.randint(0,3,(3,10))
(~arr60.any(axis=0)).any()


False

In [ ]:
#61. Find the nearest value from a given value in an array (★★☆)
#(hint: np.abs, argmin, flat)
arr61 = np.random.uniform(0,1,10)
r = 0.5
m = arr61.flat[np.abs(arr61 - r).argmin()]
print(m)

0.5480458667032035


In [ ]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
#(hint: np.nditer)
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it:
  z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
#63. Create an array class that has a name attribute (★★☆)
#(hint: class method)
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [ ]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
#(hint: np.bincount | np.add.at)
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 1. 3. 4. 2. 5. 5. 4. 1. 3.]


In [ ]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
#(hint: np.bincount)
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
#(hint: np.unique)
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [ ]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
#(hint: sum(axis=(-2,-1)))
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[40 55 43 39]
 [51 50 57 59]
 [53 52 48 41]]


In [ ]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)
#(hint: np.bincount)
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.4061093  0.33741156 0.52407785 0.32729051 0.35060643 0.39688784
 0.43875641 0.4605268  0.48715959 0.54024416]


In [ ]:
#69. How to get the diagonal of a dot product? (★★★)
#(hint: np.diag)
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.2572244 , 1.32734119, 1.73733668, 1.34928824, 1.58765891])

In [ ]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
#(hint: array[::4])
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [ ]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
#(hint: array[:, :, None])
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [ ]:
#72. How to swap two rows of an array? (★★★)
#(hint: array[[]] = array[[]])
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)
#(hint: repeat, np.roll, np.sort, view, np.unique)
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 23) ( 2, 68) ( 8, 10) ( 8, 69) (10, 69) (11, 65) (11, 98) (12, 17)
 (12, 71) (17, 71) (19, 52) (19, 80) (20, 65) (20, 82) (23, 68) (31, 32)
 (31, 42) (32, 42) (33, 58) (33, 79) (34, 67) (34, 80) (41, 59) (41, 89)
 (52, 80) (58, 79) (59, 89) (65, 82) (65, 98) (67, 80)]


In [ ]:
#74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
#(hint: np.repeat)
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [ ]:
#75. How to compute averages using a sliding window over an array? (★★★)
#(hint: np.cumsum)
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [ ]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
#(hint: from numpy.lib import stride_tricks)
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
#(hint: np.logical_not, np.negative)
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.21233368, -0.45901146,  0.62558068, -0.80916039, -0.84672382,
       -0.851215  ,  0.88772366,  0.71321615,  0.68478681, -0.82935862,
       -0.32570728, -0.55554245,  0.15390346, -0.00708237, -0.58892054,
       -0.55516813, -0.69708183,  0.59630828, -0.80128859, -0.56719087,
       -0.26208387, -0.51374968,  0.85375435,  0.7753252 , -0.75219722,
        0.13135275,  0.22231302,  0.2546729 ,  0.40444059,  0.35715364,
       -0.11318156, -0.13433921, -0.73897303, -0.93438672,  0.46131111,
       -0.09057871,  0.68950768, -0.72501281, -0.44802236,  0.78184865,
        0.87599711, -0.14397801, -0.40559534, -0.44683325,  0.79159943,
        0.39021031,  0.64133335,  0.36628757,  0.26925818,  0.85262812,
       -0.48679538, -0.99905837, -0.42865912,  0.65201755,  0.45064368,
        0.97598222,  0.0269564 , -0.60568154,  0.53841568,  0.49265408,
        0.04970712, -0.57651201, -0.69466788,  0.8519681 , -0.59475183,
        0.55810839,  0.59721388,  0.89200327,  0.49761312, -0.74

In [ ]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[3.77070774 5.55964825 3.84434087 4.5542567  7.62602364 5.63939391
 8.47965888 0.74649253 6.47101723 0.37175377]


In [ ]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.25683268  0.99701677  4.0171176  10.31622687  4.85535253 11.23392341
  10.67282847  0.5496252   7.60399517  8.10393214]
 [ 8.09562743  4.8897577   0.47280775  7.33593048  1.4583491  12.52726751
  13.82696664  4.77681043  6.82560869  7.22376565]
 [ 2.60140026  2.31990324  8.07336054  6.25173606  0.86370625  6.93602386
   6.55497742  2.96059941  3.30756123  3.81287737]
 [ 7.2756717   7.1892878   5.66231823 14.27198704  9.14358095 11.60321319
   9.38359619  6.32764406  9.75032874 10.33574205]
 [ 2.03949851  1.39115095  9.42926319  8.47667419  3.30669436  6.85015452
   5.42207812  0.47108408  4.35810835  4.9184842 ]
 [ 5.73232229  5.49220879  6.73346657 12.58811266  7.44594171 10.23810764
   8.25467634  4.61610654  8.19207911  8.76983859]
 [ 7.40725382  5.26758774  3.72585472  5.77318153  0.04574154  9.72005537
  10.63985963  5.41135853  4.55745825  4.98514976]
 [ 3.84098158  6.09013152  0.75724072 15.98430689 10.48547415 16.62594414
  15.5797934   5.81729098 13.27450487 13.78124909]


In [ ]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)
#(hint: minimum, maximum)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 0 4 9 5 9 2 2 2 2]
 [8 7 3 8 7 6 9 9 5 6]
 [6 3 2 6 7 9 4 2 7 7]
 [7 2 0 5 8 4 0 6 9 9]
 [9 5 8 1 5 9 6 1 7 6]
 [8 0 8 4 0 2 3 4 8 5]
 [2 6 7 7 0 9 7 7 8 6]
 [2 3 0 0 4 0 4 3 7 4]
 [4 4 1 4 6 7 2 4 8 3]
 [9 9 2 3 1 2 5 9 0 4]]
[[0 0 0 0 0]
 [0 2 0 4 9]
 [0 8 7 3 8]
 [0 6 3 2 6]
 [0 7 2 0 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [ ]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
#(hint: stride_tricks.as_strided)
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [ ]:
#82. Compute a matrix rank (★★★)
#(hint: np.linalg.svd) (suggestion: np.linalg.svd)
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [ ]:
#83. How to find the most frequent value in an array?
#(hint: np.bincount, argmax)
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


In [ ]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
#(hint: stride_tricks.as_strided)
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 4 1]
   [4 2 4]
   [3 0 3]]

  [[4 1 2]
   [2 4 1]
   [0 3 3]]

  [[1 2 1]
   [4 1 3]
   [3 3 0]]

  [[2 1 4]
   [1 3 3]
   [3 0 4]]

  [[1 4 4]
   [3 3 2]
   [0 4 1]]

  [[4 4 2]
   [3 2 4]
   [4 1 1]]

  [[4 2 1]
   [2 4 4]
   [1 1 1]]

  [[2 1 2]
   [4 4 1]
   [1 1 0]]]


 [[[4 2 4]
   [3 0 3]
   [4 4 3]]

  [[2 4 1]
   [0 3 3]
   [4 3 4]]

  [[4 1 3]
   [3 3 0]
   [3 4 3]]

  [[1 3 3]
   [3 0 4]
   [4 3 4]]

  [[3 3 2]
   [0 4 1]
   [3 4 4]]

  [[3 2 4]
   [4 1 1]
   [4 4 0]]

  [[2 4 4]
   [1 1 1]
   [4 0 1]]

  [[4 4 1]
   [1 1 0]
   [0 1 0]]]


 [[[3 0 3]
   [4 4 3]
   [4 3 0]]

  [[0 3 3]
   [4 3 4]
   [3 0 4]]

  [[3 3 0]
   [3 4 3]
   [0 4 1]]

  [[3 0 4]
   [4 3 4]
   [4 1 4]]

  [[0 4 1]
   [3 4 4]
   [1 4 1]]

  [[4 1 1]
   [4 4 0]
   [4 1 0]]

  [[1 1 1]
   [4 0 1]
   [1 0 3]]

  [[1 1 0]
   [0 1 0]
   [0 3 4]]]


 [[[4 4 3]
   [4 3 0]
   [3 4 1]]

  [[4 3 4]
   [3 0 4]
   [4 1 0]]

  [[3 4 3]
   [0 4 1]
   [1 0 2]]

  [[4 3 4]
   [4 1 4]
   [0 2 3]]

  [[3 4 4]
   

In [ ]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
#(hint: class method)
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2  8  0  6  1]
 [ 8  3  5  8 12]
 [ 0  5  5 42 10]
 [ 6  8 42  6 10]
 [ 1 12 10 10  3]]


In [ ]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
#(hint: np.tensordot)
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [ ]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
#(hint: np.add.reduceat)
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [ ]:
#88. How to implement the Game of Life using numpy arrays? (★★★)
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [ ]:
#89. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [ ]:
#90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
#(hint: np.indices)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [ ]:
#91. How to create a record array from a regular array? (★★★)
#(hint: np.core.records.fromarrays)
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [ ]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
#(hint: np.power, *, np.einsum)
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.8 s per loop
1 loop, best of 5: 208 ms per loop
10 loops, best of 5: 171 ms per loop


In [ ]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
#(hint: np.where)
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 4 5 6]


In [ ]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 1 1]
 [3 4 0]
 [0 2 0]
 [0 4 2]
 [2 0 1]
 [2 1 0]
 [0 1 3]
 [3 4 4]
 [3 3 4]
 [2 0 0]]
[[0 1 1]
 [3 4 0]
 [0 2 0]
 [0 4 2]
 [2 0 1]
 [2 1 0]
 [0 1 3]
 [3 4 4]
 [3 3 4]
 [2 0 0]]
[[0 1 1]
 [3 4 0]
 [0 2 0]
 [0 4 2]
 [2 0 1]
 [2 1 0]
 [0 1 3]
 [3 4 4]
 [3 3 4]
 [2 0 0]]


In [ ]:
#95. Convert a vector of ints into a matrix binary representation (★★★)
#(hint: np.unpackbits)
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [ ]:
#96. Given a two dimensional array, how to extract unique rows? (★★★)
#(hint: np.ascontiguousarray)
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


In [ ]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
#(hint: np.einsum)
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.3984606 , 0.2469821 , 0.76720478, 0.31418639, 0.26076923,
        0.71748373, 0.2494535 , 0.19225892, 0.25013847, 0.30053638],
       [0.21487271, 0.13318686, 0.41372064, 0.16942725, 0.14062166,
        0.38690821, 0.13451958, 0.10367699, 0.13488895, 0.16206639],
       [0.01284474, 0.00796169, 0.02473155, 0.01012809, 0.00840614,
        0.02312875, 0.00804136, 0.00619764, 0.00806344, 0.00968807],
       [0.30859328, 0.19127868, 0.59417227, 0.24332596, 0.20195631,
        0.55566512, 0.19319269, 0.14889756, 0.19372317, 0.23275453],
       [0.49168049, 0.30476359, 0.94669242, 0.38769032, 0.32177622,
        0.88533912, 0.30781317, 0.23723791, 0.30865839, 0.3708469 ],
       [0.1171826 , 0.07263455, 0.22562595, 0.09239854, 0.07668918,
        0.21100357, 0.07336136, 0.0565411 , 0.0735628 , 0.08838423],
       [0.48764218, 0.30226048, 0.93891697, 0.38450612, 0.31913338,
        0.87806759, 0.30528502, 0.23528941, 0.30612329, 0.36780103],
       [0.00303111, 0.00187881, 0.0058361

In [ ]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
#(hint: np.cumsum, np.interp)
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [ ]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
#(hint: np.logical_and.reduce, np.mod)
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [ ]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
#(hint: np.percentile)
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.15711975  0.19534903]
